-- Remover views
DROP VIEW IF EXISTS MoradaClientes;
DROP VIEW IF EXISTS TarifaVeiculos;

-- Remover tabelas
DROP TABLE IF EXISTS Avaliacao;
DROP TABLE IF EXISTS Pessoa;
DROP TABLE IF EXISTS Empresa;
DROP TABLE IF EXISTS Aluguer;
DROP TABLE IF EXISTS Reservas;
DROP TABLE IF EXISTS Condutor;
DROP TABLE IF EXISTS Cliente;
DROP TABLE IF EXISTS Intervencao;
DROP TABLE IF EXISTS Veiculo;
DROP TABLE IF EXISTS Tarifa;
DROP TABLE IF EXISTS TipoVeiculo;
DROP TABLE IF EXISTS Lugar;
DROP TABLE IF EXISTS ParqueEstacionamento;
DROP TABLE IF EXISTS Morada;
DROP TABLE IF EXISTS Ativos;